################################### Default Configuration ############################
baseurl = "https://inaa.netlify.app/"
title = "INAA | Wear what feels like you"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
# disable language
disableLanguages = [] # disable language from here
